language: go

go:
 - tip

before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - go get github.com/onsi/ginkgo/ginkgo
 - go get github.com/modocache/gover

script:
 - $HOME/gopath/bin/ginkgo -r  -cover -coverpkg=./GoBDD/... -trace -race
 - $HOME/gopath/bin/gover
 - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -repotoken FJWuSQHhKLOFItSb8Wwvf2uT3HYsqggjg